name: Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - front
  # pull_request:
  #     - front

jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build page
      run: npm run build
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v1
      with:
        name: react-github-actions-build
        path: build
# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "deploy"
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest

#     steps:
#     # Спуливаем содержимое
#     - uses: actions/checkout@v2

#     # Устанавливаем
#     - name: Extract branch name
#       shell: bash
#       run: |
#         echo "::set-env name=BRANCH_NAME::${GITHUB_REF##*/}"
#         echo "${{ env.BRANCH_NAME }}"
#     # Собираем контейнер
#     - name: Build and push image
#       uses: docker/build-push-action@v1.1.0
#       with:
#         repository: hw_front_${{ env.BRANCH_NAME }}
#         dockerfile: ./Dockerfile
#         registry: ${{ secrets.DOCKER_REGISTRY }}
#         username: ${{ secrets.DOCKER_LOGIN }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         tags: new
#         build_args: BRAHCH_NAME=${{ env.BRANCH_NAME }}

#     # Деплой
#     - name: Deploy prod
#       if: env.BRANCH_NAME == 'master'
#       uses: wei/curl@v1.1.1
#       with:
#         args: -X POST ${{ secrets.DEPLOY_HOST }}/modules/git/public/web-hook.php?uuid=${{ secrets.DEPLOY_FRONT_PROD_TOKEN }}

#     - name: Deploy dev
#       if: env.BRANCH_NAME == 'dev'
#       uses: wei/curl@v1.1.1
#       with:
#         args: -X POST ${{ secrets.DEPLOY_HOST }}/modules/git/public/web-hook.php?uuid=${{ secrets.DEPLOY_FRONT_DEV_TOKEN }}      